# Stack
version: "3.8"
services:
    ticketingsystem-gitlab:
        container_name: 'ticketingsystem_gitlab'
        image: 'gitlab/gitlab-ce:latest'
        restart: 'always'
        networks:
            frontend:
                ipv4_address: 172.21.0.70
        volumes:
            - 'ticketingsystem-config:/etc/gitlab'
            - 'ticketingsystem-logs:/var/log/gitlab'
            - 'ticketingsystem-data:/var/opt/gitlab'
            - 'ticketingsystem-backup:/var/opt/gitlab/backups'
        hostname: 'srv-cms03.banana.ch'
        environment:
            EXTERNAL_URL: 'https://support.banana.ch'
            BACKUP_CRONTAB: |
                SHELL=/bin/bash
                0 21 * * 1-5 root gitlab-backup create && cp /etc/gitlab/gitlab-secrets.json /var/opt/gitlab/backups/gitlab-secrets.json && cp /etc/gitlab/gitlab.rb var/opt/gitlab/backups/gitlab.rb && tar -czvf /var/opt/gitlab/backups/backup_$$(date '+%Y-%m-%d_%H-%M-%S').tar.gz /var/opt/gitlab/backups/*gitlab* && rm -f /var/opt/gitlab/backups/*.tar
            GITLAB_POST_RECONFIGURE_SCRIPT: |
                echo "$$BACKUP_CRONTAB" > "/backup-crontab"
                go-crond "/backup-crontab" &
            GITLAB_OMNIBUS_CONFIG: |
                # URL
                external_url 'https://support.banana.ch'
                letsencrypt['enable'] = false
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
                # Backup
                gitlab_rails['manage_backup_path'] = true
                gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
                gitlab_rails['backup_keep_time'] = 604800
                # Email
                ## Outgoing
                gitlab_rails['gitlab_email_enabled'] = true
                gitlab_rails['gitlab_email_from'] =  'example@example.com'
                gitlab_rails['gitlab_email_display_name'] = 'Banana Support Service'
                gitlab_rails['gitlab_email_reply_to'] =  'example@example.com'
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = 'example.com'
                gitlab_rails['smtp_port'] = 465
                gitlab_rails['smtp_user_name'] = ''
                gitlab_rails['smtp_password'] = ''
                gitlab_rails['smtp_domain'] = 'example.com'
                gitlab_rails['smtp_authentication'] = 'login'
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['smtp_tls'] = true
                gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
                ## Incoming
                gitlab_rails['incoming_email_enabled'] =  true
                gitlab_rails['incoming_email_address'] =  'example+%{key}@example.com'
                gitlab_rails['incoming_email_email'] = 'example@example.com'
                gitlab_rails['incoming_email_password'] = ''
                gitlab_rails['incoming_email_host'] = ''
                gitlab_rails['incoming_email_port'] = 993
                gitlab_rails['incoming_email_ssl'] = true
                gitlab_rails['incoming_email_start_tls'] = false
                gitlab_rails['incoming_email_mailbox_name'] = 'inbox'
                gitlab_rails['incoming_email_idle_timeout'] = 60
                gitlab_rails['incoming_email_expunge_deleted'] = false
                gitlab_rails['service_desk_custom_address'] = true
                # Default project feature settings
                gitlab_rails['gitlab_default_projects_features_issues'] = true
                gitlab_rails['gitlab_default_projects_features_merge_requests'] = false
                gitlab_rails['gitlab_default_projects_features_wiki'] = true
                gitlab_rails['gitlab_default_projects_features_snippets'] = false
                gitlab_rails['gitlab_default_projects_features_builds'] = false
                gitlab_rails['gitlab_default_projects_features_container_registry'] = false
                # OmniAuth (Azure)
                gitlab_rails['omniauth_enabled'] = true
                gitlab_rails['omniauth_auto_link_user'] = ['azure_oauth2']
                gitlab_rails['omniauth_external_providers'] = ['azure_oauth2']
                gitlab_rails['omniauth_providers'] = [
                    {
                        "name" => "azure_oauth2",
                        "args" => {
                            "client_id" => "REDACTED",
                            "client_secret" => "REDACTED",
                            "tenant_id" => "REDACTED",
                        }
                    }
                ]
                # SSH
                gitlab_rails['gitlab_shell_ssh_port'] = 7402


    ticketingsystem-chatbox:
        container_name: 'ticketingsystem_chatbox'
        build:
            context: ../ticketing
            dockerfile: ChatBox.Dockerfile
        image: ticketingsystem_chatbox:latest
        networks:
            frontend:
        restart: always
        env_file:
            - ../ticketing/chatbox/variables.env

volumes:
    ticketingsystem-config:
    ticketingsystem-logs:
    ticketingsystem-data:
    ticketingsystem-backup:
    ticketingsystem-chatbox:

networks:
    frontend:
        external: true
