# Stack
version: "3.8"
services:
    ticketingsystem-gitlab:
        container_name: 'ticketingsystem_gitlab'
        image: 'gitlab/gitlab-ce:13.4.3-ce.0'
        restart: 'always'
        networks:
            frontend:
                ipv4_address: 172.21.0.70
        volumes:
            - 'ticketingsystem-config:/etc/gitlab'
            - 'ticketingsystem-logs:/var/log/gitlab'
            - 'ticketingsystem-data:/var/opt/gitlab'
        hostname: 'srv-cms03.banana.ch'
        environment:
            EXTERNAL_URL: 'https://support.banana.ch'
            # TODO: Spostare le variabili nel file secret
            GITLAB_OMNIBUS_CONFIG: |
                # URL
                external_url 'https://support.banana.ch'
                letsencrypt['enable'] = false
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
                # Backup
                gitlab_rails['manage_backup_path'] = true
                gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'
                gitlab_rails['backup_keep_time'] = 604800
                # Email
                ## Outgoing
                gitlab_rails['gitlab_email_enabled'] = true
                gitlab_rails['gitlab_email_from'] =  'bnn.fieldproject@gmail.com'
                gitlab_rails['gitlab_email_display_name'] = 'Banana Support Service'
                gitlab_rails['gitlab_email_reply_to'] =  'example@gmail.com'
                gitlab_rails['smtp_enable'] = true
                gitlab_rails['smtp_address'] = 'smtp.gmail.com'
                gitlab_rails['smtp_port'] = 587
                gitlab_rails['smtp_user_name'] = 'example@gmail.com'
                # gitlab_rails['smtp_password'] = ''
                gitlab_rails['smtp_domain'] = 'smtp.gmail.com'
                gitlab_rails['smtp_authentication'] = 'login'
                gitlab_rails['smtp_enable_starttls_auto'] = true
                gitlab_rails['smtp_tls'] = false
                gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
                ## Incoming
                gitlab_rails['incoming_email_enabled'] =  true
                gitlab_rails['incoming_email_address'] =  'example+%{key}@gmail.com'
                gitlab_rails['incoming_email_email'] = 'example@gmail.com'
                # gitlab_rails['incoming_email_password'] = ''
                gitlab_rails['incoming_email_host'] = 'imap.gmail.com'
                gitlab_rails['incoming_email_port'] = 993
                gitlab_rails['incoming_email_ssl'] = true
                gitlab_rails['incoming_email_start_tls'] = false
                gitlab_rails['incoming_email_mailbox_name'] = 'inbox'
                gitlab_rails['incoming_email_idle_timeout'] = 60
                gitlab_rails['incoming_email_expunge_deleted'] = false
                # Default project feature settings
                gitlab_rails['gitlab_default_projects_features_issues'] = true
                gitlab_rails['gitlab_default_projects_features_merge_requests'] = false
                gitlab_rails['gitlab_default_projects_features_wiki'] = true
                gitlab_rails['gitlab_default_projects_features_snippets'] = false
                gitlab_rails['gitlab_default_projects_features_builds'] = false
                gitlab_rails['gitlab_default_projects_features_container_registry'] = false
                # OmniAuth (Azure)
                # gitlab_rails['omniauth_enabled'] = true
                # gitlab_rails['omniauth_auto_link_user'] = ['azure_oauth2']
                # gitlab_rails['omniauth_external_providers'] = ['azure_oauth2']
                # gitlab_rails['omniauth_providers'] = [
                #    {
                #        "name" => "azure_oauth2",
                #        "args" => { "client_id" => "REDACTED", "client_secret" => "REDACTED", "tenant_id" => "REDACTED", }
                #    }
                #
                # SSH
                gitlab_rails['gitlab_shell_ssh_port'] = 7402


    ticketingsystem-chatbox:
        container_name: 'ticketingsystem_chatbox'
        build:
            context: ../ticketing
            dockerfile: ChatBox.Dockerfile
        image: ticketingsystem_chatbox:latest
        networks:
            frontend:
        restart: always
        env_file:
            - ../ticketing/chatbox.env

volumes:
    ticketingsystem-config:
    ticketingsystem-logs:
    ticketingsystem-data:
    ticketingsystem-chatbox:

networks:
    frontend:
        external: true
